export default interface HTML {
	[key: string]: any;

	caseSensitive?: Boolean;

	collapseBooleanAttributes?: Boolean;

	collapseInlineTagWhitespace?: Boolean;

	collapseWhitespace?: Boolean;

	conservativeCollapse?: Boolean;

	continueOnParseError?: Boolean;

	customAttrAssign?: RegExp[];

	customAttrCollapse?: RegExp;

	customAttrSurround?: RegExp[];

	customEventAttributes?: RegExp[];

	decodeEntities?: Boolean;

	html5?: Boolean;

	ignoreCustomComments?: RegExp[];

	ignoreCustomFragments?: RegExp[];

	includeAutoGeneratedTags?: Boolean;

	keepClosingSlash?: Boolean;

	maxLineLength?: Number | null;

	minifyCSS?:
		| Boolean
		| Object
		| (({}: { text: string; type: string }) => void);

	minifyJS?:
		| Boolean
		| Object
		| (({}: { text: string; inline: string }) => void);

	minifyURLs?: Boolean | String | Object | (({}: { text: string }) => void);

	noNewlinesBeforeTagClose?: Boolean;

	preserveLineBreaks?: Boolean;

	preventAttributesEscaping?: Boolean;

	processConditionalComments?: Boolean;

	processScripts?: String[];

	quoteCharacter?: String;

	removeAttributeQuotes?: Boolean;

	removeComments?: Boolean;

	removeEmptyAttributes?:
		| Boolean
		| (({}: { attrName: string; tag: string }) => void);

	removeEmptyElements?: Boolean;

	removeOptionalTags?: Boolean;

	removeRedundantAttributes?: Boolean;

	removeScriptTypeAttributes?: Boolean;

	removeStyleLinkTypeAttributes?: Boolean;

	removeTagWhitespace?: Boolean;

	sortAttributes?: Boolean;

	sortClassName?: Boolean;

	trimCustomFragments?: Boolean;

	useShortDoctype?: Boolean;
}
