import type { Options } from "html-minifier-terser";

export interface HTML extends Options {
	// rome-ignore lint/suspicious/noExplicitAny:
	[key: string]: any;
}

export default {
	caseSensitive: true,
	collapseInlineTagWhitespace: false,
	collapseWhitespace: true,
	continueOnParseError: true,
	html5: true,
	includeAutoGeneratedTags: true,
	keepClosingSlash: true,
	minifyCSS: true,
	minifyJS: true,
	minifyURLs: false,
	preventAttributesEscaping: false,
	processConditionalComments: false,
	removeAttributeQuotes: true,
	removeComments: true,
	ignoreCustomComments: [/^\s*#/, /^\s*\[/, /^\s*\]/, /^\s*!/, /^\s*\//],
	removeScriptTypeAttributes: true,
	removeStyleLinkTypeAttributes: true,
	removeTagWhitespace: false,
	sortAttributes: true,
	sortClassName: true,
	trimCustomFragments: true,
	useShortDoctype: false,
	noNewlinesBeforeTagClose: true,
	quoteCharacter: '"',
} satisfies HTML;
